Improve error messages of bootstrap

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -8,12 +8,15 @@
 
 # override by option argument
 SC_CONFIG="sc/config"
-if test -n "$1" ; then
+if test "x$1" != x ; then
   SC_CONFIG="$1"
-  if test ! -d "$SC_CONFIG" ; then
-    echo "Cannot find directory $SC_CONFIG"
-    exit 1
-  fi
+fi
+if test ! -d "$SC_CONFIG" ; then
+  echo "Error: Cannot find directory $SC_CONFIG"
+  echo "   If you just called ./bootstrap from a fresh clone of hopest,"
+  echo "   you may need to checkout the submodules sc and p4est:"
+  echo "   \$ git submodule init && git submodule update"
+  exit 1
 fi
 # convert into an absolute path
 SC_CONFIG=`cd "$SC_CONFIG" && pwd`
@@ -27,12 +30,15 @@ fi
 
 #override by option argument
 P4EST_CONFIG="p4est/config"
-if test -n "$2" ; then
+if test "x$2" != x ; then
   P4EST_CONFIG="$2"
-  if test ! -d "$P4EST_CONFIG" ; then
-    echo "Cannot find directory $P4EST_CONFIG"
-    exit 
-  fi
+fi
+if test ! -d "$P4EST_CONFIG" ; then
+  echo "Error: Cannot find directory $P4EST_CONFIG"
+  echo "   If you just called ./bootstrap from a fresh clone of hopest,"
+  echo "   you may need to checkout the submodules sc and p4est:"
+  echo "   \$ git submodule init && git submodule update"
+  exit 1
 fi
 #convert into an absolute path
 P4EST_CONFIG=`cd "$P4EST_CONFIG" && pwd`
@@ -41,6 +47,8 @@ if test -x "p4est/bootstrap" ; then
   echo "Running bootstrap in subdirectory p4est"
   (cd p4est && ./bootstrap "$SC_CONFIG")
 fi
+
+# RUNNING BOOTSTRAP FOR HOPEST
 
 echo "--- This is the bootstrap script for hopest ---"
 echo "Current directory is $PWD"
